name: Pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest

    container:
      image: docker://ghcr.io/jpaztech/blog-build-tools:latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Initialize
        run: |
          cp -r /blog/* .
          git submodule update -i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
