name: release-build-tools

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - name: Set short SHA
        id: short_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c 1-8)"

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_BASE_NAME }}:${{ github.event.release.tag_name }}
            ${{ env.DOCKER_BASE_NAME }}:${{ steps.short_sha.outputs.sha8 }}
            ${{ env.DOCKER_BASE_NAME }}:latest
