name: release-build-tools

on:
  release:
    types:
      - published

env:
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${DOCKER_BASE_NAME}:${GITHUB_SHA::8}
            ${DOCKER_BASE_NAME}:${{ github.event.release.tag_name }}
            ${DOCKER_BASE_NAME}:latest
